// TOEFL 필수 단어 데이터베이스
// 각 항목: w(단어), p(품사), k(한국어 뜻), s(동의어 목록), a(반의어 목록, 없으면 빈 배열)
// 새 단어를 추가하려면 이 배열에 같은 형식으로 객체를 추가하면 됩니다.
const TOEFL_WORDS = [
{w:"abate",p:"v.",k:"약화되다, 누그러지다",s:["subside","diminish","wane","recede"],a:["intensify","escalate"]},
{w:"aberrant",p:"adj.",k:"정상에서 벗어난, 비정상적인",s:["anomalous","atypical","deviant"],a:["normal","typical"]},
{w:"abscond",p:"v.",k:"몰래 달아나다",s:["flee","bolt","decamp"],a:["remain","stay"]},
{w:"abstain",p:"v.",k:"삼가다, 자제하다",s:["refrain","forgo","desist"],a:["indulge","partake"]},
{w:"accolade",p:"n.",k:"칭찬, 영예",s:["praise","tribute","honor"],a:["criticism","condemnation"]},
{w:"acumen",p:"n.",k:"통찰력, 예리함",s:["shrewdness","insight","sagacity"],a:["ineptitude","obtuseness"]},
{w:"adhere",p:"v.",k:"고수하다, 들러붙다",s:["stick","cling","comply"],a:["deviate","abandon"]},
{w:"adjacent",p:"adj.",k:"인접한",s:["adjoining","neighboring","bordering"],a:["distant","remote"]},
{w:"adroit",p:"adj.",k:"능숙한, 재치 있는",s:["skillful","deft","dexterous"],a:["clumsy","inept"]},
{w:"aesthetic",p:"adj.",k:"미적인",s:["artistic","tasteful","visual"],a:["unaesthetic","ugly"]},
{w:"affluent",p:"adj.",k:"부유한, 풍족한",s:["wealthy","prosperous","opulent"],a:["poor","destitute"]},
{w:"aggregate",p:"n./v.",k:"집합체; 총계를 내다",s:["total","sum","combine"],a:["separate","disperse"]},
{w:"alleviate",p:"v.",k:"완화하다, 경감하다",s:["relieve","mitigate","ease"],a:["aggravate","worsen"]},
{w:"ambiguous",p:"adj.",k:"애매모호한",s:["equivocal","vague","unclear"],a:["clear","unambiguous"]},
{w:"ambivalent",p:"adj.",k:"양가적인, 상반된 감정의",s:["conflicted","uncertain","torn"],a:["decisive","certain"]},
{w:"amiable",p:"adj.",k:"상냥한, 붙임성 있는",s:["friendly","affable","genial"],a:["hostile","unfriendly"]},
{w:"amplify",p:"v.",k:"증폭시키다, 확대하다",s:["intensify","magnify","boost"],a:["diminish","reduce"]},
{w:"analogous",p:"adj.",k:"유사한, 비슷한",s:["similar","comparable","parallel"],a:["different","dissimilar"]},
{w:"anomaly",p:"n.",k:"이례, 변칙",s:["irregularity","deviation","aberration"],a:["norm","regularity"]},
{w:"antagonist",p:"n.",k:"적대자, 반대자",s:["adversary","opponent","rival"],a:["ally","protagonist"]},
{w:"apathy",p:"n.",k:"무관심, 냉담",s:["indifference","detachment","listlessness"],a:["enthusiasm","passion"]},
{w:"appease",p:"v.",k:"달래다, 진정시키다",s:["placate","pacify","mollify"],a:["provoke","incite"]},
{w:"arbitrary",p:"adj.",k:"임의적인, 자의적인",s:["random","capricious","discretionary"],a:["reasoned","systematic"]},
{w:"arduous",p:"adj.",k:"고된, 힘든",s:["strenuous","laborious","grueling"],a:["easy","effortless"]},
{w:"articulate",p:"v./adj.",k:"또렷이 말하다; 명료한",s:["express","enunciate","eloquent"],a:["mumble","incoherent"]},
{w:"ascertain",p:"v.",k:"확인하다, 알아내다",s:["determine","verify","confirm"],a:["guess","assume"]},
{w:"assiduous",p:"adj.",k:"근면한, 부지런한",s:["diligent","industrious","meticulous"],a:["lazy","negligent"]},
{w:"astute",p:"adj.",k:"영리한, 통찰력 있는",s:["shrewd","perceptive","sharp"],a:["obtuse","naive"]},
{w:"augment",p:"v.",k:"증대시키다",s:["increase","enhance","supplement"],a:["diminish","reduce"]},
{w:"austere",p:"adj.",k:"엄격한, 검소한",s:["stern","severe","spartan"],a:["luxurious","lavish"]},
{w:"autonomous",p:"adj.",k:"자주적인, 독립적인",s:["independent","self-governing","sovereign"],a:["dependent","subordinate"]},
{w:"aversion",p:"n.",k:"혐오, 반감",s:["distaste","antipathy","repugnance"],a:["fondness","affinity"]},
{w:"banal",p:"adj.",k:"진부한",s:["trite","hackneyed","clichéd"],a:["original","novel"]},
{w:"belie",p:"v.",k:"거짓임을 보여주다, 착각하게 만들다",s:["contradict","misrepresent","disguise"],a:["confirm","reveal"]},
{w:"benevolent",p:"adj.",k:"자애로운, 선의의",s:["kind","charitable","altruistic"],a:["malevolent","cruel"]},
{w:"bewilder",p:"v.",k:"당황하게 하다, 혼란스럽게 하다",s:["confuse","perplex","baffle"],a:["clarify","enlighten"]},
{w:"bias",p:"n.",k:"편견, 편향",s:["prejudice","partiality","slant"],a:["fairness","impartiality"]},
{w:"blatant",p:"adj.",k:"노골적인, 뻔뻔한",s:["flagrant","conspicuous","glaring"],a:["subtle","discreet"]},
{w:"bolster",p:"v.",k:"강화하다, 지지하다",s:["reinforce","support","strengthen"],a:["undermine","weaken"]},
{w:"brevity",p:"n.",k:"간결함, 짧음",s:["conciseness","succinctness","terseness"],a:["verbosity","prolixity"]},
{w:"buoyant",p:"adj.",k:"활기찬, 낙관적인; 부력이 있는",s:["cheerful","resilient","optimistic"],a:["gloomy","despondent"]},
{w:"candid",p:"adj.",k:"솔직한",s:["frank","forthright","honest"],a:["evasive","deceptive"]},
{w:"capricious",p:"adj.",k:"변덕스러운",s:["fickle","erratic","whimsical"],a:["consistent","steady"]},
{w:"catalyst",p:"n.",k:"촉매, 계기",s:["stimulus","trigger","impetus"],a:["deterrent","hindrance"]},
{w:"caustic",p:"adj.",k:"신랄한, 부식성의",s:["scathing","biting","corrosive"],a:["gentle","mild"]},
{w:"chronic",p:"adj.",k:"만성적인",s:["persistent","recurring","perpetual"],a:["temporary","acute"]},
{w:"coherent",p:"adj.",k:"일관성 있는, 논리정연한",s:["logical","consistent","lucid"],a:["incoherent","disjointed"]},
{w:"complacent",p:"adj.",k:"자기만족적인, 안일한",s:["self-satisfied","smug","unconcerned"],a:["vigilant","dissatisfied"]},
{w:"comprehensive",p:"adj.",k:"포괄적인",s:["thorough","extensive","exhaustive"],a:["limited","partial"]},
{w:"concise",p:"adj.",k:"간결한",s:["succinct","terse","brief"],a:["verbose","wordy"]},
{w:"condone",p:"v.",k:"묵인하다, 눈감아주다",s:["overlook","tolerate","excuse"],a:["condemn","denounce"]},
{w:"congruent",p:"adj.",k:"일치하는, 합동인",s:["consistent","compatible","corresponding"],a:["incongruent","conflicting"]},
{w:"conspicuous",p:"adj.",k:"눈에 띄는, 두드러진",s:["noticeable","prominent","striking"],a:["inconspicuous","unnoticeable"]},
{w:"contentious",p:"adj.",k:"논쟁적인",s:["controversial","disputatious","divisive"],a:["undisputed","agreeable"]},
{w:"convoluted",p:"adj.",k:"복잡한, 뒤얽힌",s:["complex","intricate","elaborate"],a:["simple","straightforward"]},
{w:"copious",p:"adj.",k:"풍부한, 대량의",s:["abundant","plentiful","ample"],a:["scarce","meager"]},
{w:"credible",p:"adj.",k:"믿을 만한",s:["believable","plausible","trustworthy"],a:["incredible","dubious"]},
{w:"criteria",p:"n.",k:"기준 (criterion의 복수)",s:["standards","benchmarks","measures"],a:[]},
{w:"cryptic",p:"adj.",k:"불가사의한, 난해한",s:["enigmatic","obscure","mysterious"],a:["clear","transparent"]},
{w:"cumulative",p:"adj.",k:"누적되는",s:["accumulated","aggregate","incremental"],a:["isolated","singular"]},
{w:"cursory",p:"adj.",k:"대충하는, 피상적인",s:["superficial","hasty","perfunctory"],a:["thorough","meticulous"]},
{w:"curtail",p:"v.",k:"축소하다, 제한하다",s:["reduce","restrict","truncate"],a:["extend","expand"]},
{w:"daunting",p:"adj.",k:"주눅 들게 하는, 벅찬",s:["intimidating","formidable","overwhelming"],a:["encouraging","reassuring"]},
{w:"debilitate",p:"v.",k:"쇠약하게 하다",s:["weaken","enfeeble","incapacitate"],a:["strengthen","invigorate"]},
{w:"deduce",p:"v.",k:"추론하다",s:["infer","conclude","reason"],a:["induce","assume"]},
{w:"deference",p:"n.",k:"존중, 경의",s:["respect","reverence","regard"],a:["disrespect","defiance"]},
{w:"deleterious",p:"adj.",k:"해로운",s:["harmful","detrimental","injurious"],a:["beneficial","salutary"]},
{w:"demise",p:"n.",k:"종말, 사망",s:["death","end","downfall"],a:["birth","rise"]},
{w:"deplete",p:"v.",k:"고갈시키다",s:["exhaust","drain","consume"],a:["replenish","restore"]},
{w:"deride",p:"v.",k:"조롱하다",s:["mock","ridicule","scorn"],a:["praise","admire"]},
{w:"despondent",p:"adj.",k:"낙담한",s:["dejected","downhearted","disheartened"],a:["hopeful","cheerful"]},
{w:"deter",p:"v.",k:"단념시키다, 저지하다",s:["discourage","dissuade","prevent"],a:["encourage","incite"]},
{w:"deviate",p:"v.",k:"벗어나다, 일탈하다",s:["diverge","depart","stray"],a:["conform","adhere"]},
{w:"diligent",p:"adj.",k:"근면한",s:["hardworking","industrious","assiduous"],a:["lazy","idle"]},
{w:"diminish",p:"v.",k:"줄어들다, 감소시키다",s:["decrease","reduce","dwindle"],a:["increase","augment"]},
{w:"discord",p:"n.",k:"불화, 불일치",s:["conflict","disagreement","strife"],a:["harmony","concord"]},
{w:"discreet",p:"adj.",k:"신중한, 조심스러운",s:["prudent","tactful","circumspect"],a:["indiscreet","careless"]},
{w:"disparage",p:"v.",k:"폄하하다, 얕보다",s:["belittle","denigrate","deprecate"],a:["praise","commend"]},
{w:"disparate",p:"adj.",k:"이질적인, 서로 다른",s:["dissimilar","distinct","incongruous"],a:["similar","alike"]},
{w:"dissent",p:"n./v.",k:"반대(하다), 이의(를 제기하다)",s:["disagreement","objection","opposition"],a:["consent","agreement"]},
{w:"distinct",p:"adj.",k:"뚜렷한, 별개의",s:["clear","separate","discrete"],a:["indistinct","vague"]},
{w:"diverge",p:"v.",k:"갈라지다, 나뉘다",s:["separate","split","deviate"],a:["converge","merge"]},
{w:"dogmatic",p:"adj.",k:"독단적인",s:["opinionated","doctrinaire","rigid"],a:["open-minded","flexible"]},
{w:"dubious",p:"adj.",k:"의심스러운",s:["doubtful","questionable","suspect"],a:["certain","unquestionable"]},
{w:"duration",p:"n.",k:"지속 기간",s:["span","period","length"],a:["instant","moment"]},
{w:"eclectic",p:"adj.",k:"다방면에 걸친, 절충적인",s:["diverse","varied","wide-ranging"],a:["narrow","uniform"]},
{w:"elicit",p:"v.",k:"이끌어내다, 유도하다",s:["evoke","draw out","provoke"],a:["suppress","withhold"]},
{w:"eloquent",p:"adj.",k:"웅변적인, 설득력 있는",s:["articulate","fluent","expressive"],a:["inarticulate","tongue-tied"]},
{w:"elusive",p:"adj.",k:"이해하기 어려운, 포착하기 힘든",s:["evasive","intangible","hard to grasp"],a:["obvious","evident"]},
{w:"emulate",p:"v.",k:"모방하다, 본받다",s:["imitate","mimic","replicate"],a:["originate","diverge from"]},
{w:"endemic",p:"adj.",k:"고유의, 특정 지역에 한정된",s:["native","indigenous","prevalent"],a:["foreign","introduced"]},
{w:"enervate",p:"v.",k:"기력을 빼앗다",s:["weaken","debilitate","sap"],a:["invigorate","energize"]},
{w:"engender",p:"v.",k:"낳다, 유발하다",s:["generate","produce","cause"],a:["prevent","eliminate"]},
{w:"enhance",p:"v.",k:"향상시키다",s:["improve","augment","boost"],a:["diminish","impair"]},
{w:"enigma",p:"n.",k:"수수께끼",s:["mystery","puzzle","conundrum"],a:["certainty","clarity"]},
{w:"ephemeral",p:"adj.",k:"덧없는, 순식간의",s:["transient","fleeting","momentary"],a:["permanent","enduring"]},
{w:"equanimity",p:"n.",k:"침착함, 평정",s:["composure","calmness","poise"],a:["agitation","anxiety"]},
{w:"equivocal",p:"adj.",k:"애매한, 모호한",s:["ambiguous","vague","uncertain"],a:["unequivocal","clear"]},
{w:"erratic",p:"adj.",k:"변덕스러운, 불규칙한",s:["unpredictable","inconsistent","irregular"],a:["consistent","steady"]},
{w:"erudite",p:"adj.",k:"박식한",s:["learned","scholarly","knowledgeable"],a:["ignorant","uneducated"]},
{w:"esoteric",p:"adj.",k:"난해한, 소수만 아는",s:["obscure","abstruse","arcane"],a:["mainstream","common"]},
{w:"evoke",p:"v.",k:"불러일으키다",s:["elicit","stir","summon"],a:["suppress","stifle"]},
{w:"exacerbate",p:"v.",k:"악화시키다",s:["aggravate","worsen","intensify"],a:["alleviate","improve"]},
{w:"exemplary",p:"adj.",k:"모범적인",s:["model","commendable","ideal"],a:["deficient","poor"]},
{w:"exhaustive",p:"adj.",k:"철저한, 완전한",s:["thorough","comprehensive","complete"],a:["cursory","incomplete"]},
{w:"exorbitant",p:"adj.",k:"과도한, 터무니없는",s:["excessive","extortionate","outrageous"],a:["reasonable","moderate"]},
{w:"extraneous",p:"adj.",k:"관련 없는, 불필요한",s:["irrelevant","superfluous","unrelated"],a:["relevant","essential"]},
{w:"facetious",p:"adj.",k:"경박한, 농담조의",s:["flippant","glib","frivolous"],a:["serious","earnest"]},
{w:"fallacy",p:"n.",k:"오류, 궤변",s:["misconception","error","delusion"],a:["truth","fact"]},
{w:"feasible",p:"adj.",k:"실행 가능한",s:["viable","achievable","practicable"],a:["infeasible","impractical"]},
{w:"fervent",p:"adj.",k:"열렬한",s:["passionate","ardent","zealous"],a:["indifferent","apathetic"]},
{w:"fickle",p:"adj.",k:"변덕스러운",s:["capricious","inconstant","volatile"],a:["steadfast","constant"]},
{w:"flagrant",p:"adj.",k:"명백한, 노골적인",s:["blatant","glaring","conspicuous"],a:["subtle","concealed"]},
{w:"fortuitous",p:"adj.",k:"우연한, 뜻밖의",s:["accidental","serendipitous","chance"],a:["planned","deliberate"]},
{w:"foster",p:"v.",k:"육성하다, 촉진하다",s:["nurture","promote","cultivate"],a:["hinder","suppress"]},
{w:"frugal",p:"adj.",k:"검소한",s:["thrifty","economical","sparing"],a:["extravagant","wasteful"]},
{w:"futile",p:"adj.",k:"헛된, 소용없는",s:["useless","fruitless","vain"],a:["effective","fruitful"]},
{w:"garrulous",p:"adj.",k:"수다스러운",s:["talkative","loquacious","voluble"],a:["taciturn","reticent"]},
{w:"gauge",p:"v.",k:"측정하다, 판단하다",s:["measure","assess","estimate"],a:["ignore","overlook"]},
{w:"genuine",p:"adj.",k:"진짜의, 진실한",s:["authentic","real","sincere"],a:["fake","counterfeit"]},
{w:"gratuitous",p:"adj.",k:"불필요한, 무상의",s:["unwarranted","unnecessary","unfounded"],a:["justified","warranted"]},
{w:"gregarious",p:"adj.",k:"사교적인",s:["sociable","outgoing","convivial"],a:["reclusive","introverted"]},
{w:"hackneyed",p:"adj.",k:"진부한",s:["clichéd","trite","banal"],a:["original","fresh"]},
{w:"hamper",p:"v.",k:"방해하다",s:["hinder","impede","obstruct"],a:["facilitate","assist"]},
{w:"haphazard",p:"adj.",k:"무계획적인, 되는 대로의",s:["random","disorganized","aimless"],a:["systematic","methodical"]},
{w:"hapless",p:"adj.",k:"불운한",s:["unlucky","ill-fated","unfortunate"],a:["fortunate","lucky"]},
{w:"hedonism",p:"n.",k:"쾌락주의",s:["self-indulgence","sensualism","epicureanism"],a:["asceticism","abstinence"]},
{w:"hierarchy",p:"n.",k:"위계, 계층",s:["ranking","order","gradation"],a:["equality","chaos"]},
{w:"homogeneous",p:"adj.",k:"동질적인",s:["uniform","consistent","similar"],a:["heterogeneous","diverse"]},
{w:"hypothesis",p:"n.",k:"가설",s:["theory","assumption","premise"],a:["fact","conclusion"]},
{w:"iconoclast",p:"n.",k:"인습 타파자",s:["rebel","dissenter","nonconformist"],a:["conformist","traditionalist"]},
{w:"idiosyncrasy",p:"n.",k:"특이성, 특유의 버릇",s:["quirk","peculiarity","eccentricity"],a:["normalcy","conformity"]},
{w:"ignominious",p:"adj.",k:"수치스러운",s:["disgraceful","humiliating","shameful"],a:["honorable","glorious"]},
{w:"imminent",p:"adj.",k:"임박한",s:["impending","forthcoming","looming"],a:["distant","remote"]},
{w:"immutable",p:"adj.",k:"변경할 수 없는",s:["unchangeable","fixed","permanent"],a:["mutable","changeable"]},
{w:"impartial",p:"adj.",k:"공정한",s:["unbiased","neutral","objective"],a:["biased","partisan"]},
{w:"impetuous",p:"adj.",k:"충동적인, 성급한",s:["rash","impulsive","hasty"],a:["cautious","deliberate"]},
{w:"implicit",p:"adj.",k:"암묵적인",s:["implied","tacit","unspoken"],a:["explicit","overt"]},
{w:"impute",p:"v.",k:"~의 탓으로 돌리다",s:["attribute","ascribe","credit"],a:["absolve","disclaim"]},
{w:"inadvertent",p:"adj.",k:"의도치 않은",s:["unintentional","accidental","unplanned"],a:["deliberate","intentional"]},
{w:"incessant",p:"adj.",k:"끊임없는",s:["ceaseless","constant","unrelenting"],a:["intermittent","occasional"]},
{w:"incongruous",p:"adj.",k:"어울리지 않는, 부조화한",s:["inconsistent","discordant","out of place"],a:["congruous","fitting"]},
{w:"indelible",p:"adj.",k:"지울 수 없는",s:["permanent","ineradicable","lasting"],a:["temporary","erasable"]},
{w:"indifferent",p:"adj.",k:"무관심한",s:["apathetic","unconcerned","detached"],a:["enthusiastic","passionate"]},
{w:"indigenous",p:"adj.",k:"토착의",s:["native","aboriginal","endemic"],a:["foreign","imported"]},
{w:"indolent",p:"adj.",k:"게으른",s:["lazy","idle","slothful"],a:["industrious","diligent"]},
{w:"ineffable",p:"adj.",k:"형언할 수 없는",s:["indescribable","inexpressible","unspeakable"],a:["describable","expressible"]},
{w:"inept",p:"adj.",k:"서투른, 무능한",s:["incompetent","clumsy","unskillful"],a:["adept","competent"]},
{w:"inevitable",p:"adj.",k:"불가피한",s:["unavoidable","certain","inescapable"],a:["avoidable","preventable"]},
{w:"infer",p:"v.",k:"추론하다",s:["deduce","conclude","surmise"],a:["state","declare"]},
{w:"ingenious",p:"adj.",k:"독창적인, 기발한",s:["inventive","clever","resourceful"],a:["unimaginative","dull"]},
{w:"inherent",p:"adj.",k:"내재된, 고유의",s:["intrinsic","innate","built-in"],a:["extrinsic","acquired"]},
{w:"innate",p:"adj.",k:"타고난",s:["inborn","inherent","natural"],a:["acquired","learned"]},
{w:"innocuous",p:"adj.",k:"무해한",s:["harmless","benign","inoffensive"],a:["harmful","noxious"]},
{w:"insipid",p:"adj.",k:"밋밋한, 재미없는",s:["bland","dull","vapid"],a:["flavorful","vivid"]},
{w:"integral",p:"adj.",k:"필수적인, 완전한",s:["essential","fundamental","intrinsic"],a:["peripheral","incidental"]},
{w:"intractable",p:"adj.",k:"다루기 힘든, 고집스러운",s:["stubborn","unmanageable","obstinate"],a:["tractable","manageable"]},
{w:"intransigent",p:"adj.",k:"타협하지 않는",s:["uncompromising","obstinate","inflexible"],a:["flexible","accommodating"]},
{w:"intrepid",p:"adj.",k:"대담한, 용맹한",s:["fearless","bold","valiant"],a:["timid","fearful"]},
{w:"inundate",p:"v.",k:"범람시키다, 쇄도하다",s:["flood","overwhelm","deluge"],a:["deprive","drain"]},
{w:"invariable",p:"adj.",k:"변함없는",s:["constant","unchanging","consistent"],a:["variable","fluctuating"]},
{w:"irascible",p:"adj.",k:"화를 잘 내는",s:["irritable","short-tempered","testy"],a:["easygoing","calm"]},
{w:"judicious",p:"adj.",k:"신중한, 현명한",s:["prudent","sensible","wise"],a:["injudicious","reckless"]},
{w:"juxtapose",p:"v.",k:"나란히 놓다, 병치하다",s:["contrast","compare","align"],a:["separate","isolate"]},
{w:"laconic",p:"adj.",k:"말이 없는, 간결한",s:["terse","concise","succinct"],a:["verbose","talkative"]},
{w:"lament",p:"v./n.",k:"슬퍼하다, 애도하다",s:["mourn","grieve","bemoan"],a:["celebrate","rejoice"]},
{w:"latent",p:"adj.",k:"잠재된",s:["hidden","dormant","potential"],a:["overt","manifest"]},
{w:"laud",p:"v.",k:"칭찬하다",s:["praise","commend","extol"],a:["criticize","condemn"]},
{w:"lethargic",p:"adj.",k:"무기력한",s:["sluggish","listless","drowsy"],a:["energetic","vigorous"]},
{w:"levity",p:"n.",k:"경솔함, 가벼움",s:["frivolity","flippancy","jocularity"],a:["gravity","seriousness"]},
{w:"lucid",p:"adj.",k:"명료한",s:["clear","coherent","transparent"],a:["confusing","obscure"]},
{w:"lucrative",p:"adj.",k:"수익성이 좋은",s:["profitable","remunerative","gainful"],a:["unprofitable","costly"]},
{w:"magnanimous",p:"adj.",k:"관대한, 아량 있는",s:["generous","charitable","big-hearted"],a:["petty","selfish"]},
{w:"malleable",p:"adj.",k:"유순한, 순응성 있는",s:["pliable","adaptable","flexible"],a:["rigid","inflexible"]},
{w:"mandate",p:"n./v.",k:"명령, 지시(하다)",s:["directive","decree","order"],a:["prohibition","request"]},
{w:"meager",p:"adj.",k:"빈약한, 부족한",s:["scanty","sparse","insufficient"],a:["abundant","ample"]},
{w:"mediate",p:"v.",k:"중재하다",s:["arbitrate","intervene","reconcile"],a:["provoke","instigate"]},
{w:"meticulous",p:"adj.",k:"꼼꼼한",s:["thorough","fastidious","precise"],a:["careless","sloppy"]},
{w:"mimic",p:"v.",k:"모방하다, 흉내내다",s:["imitate","emulate","copy"],a:["originate","differ"]},
{w:"mitigate",p:"v.",k:"완화하다",s:["alleviate","lessen","ease"],a:["aggravate","intensify"]},
{w:"mundane",p:"adj.",k:"평범한, 세속적인",s:["ordinary","routine","commonplace"],a:["extraordinary","exotic"]},
{w:"myriad",p:"n./adj.",k:"무수한 (수)",s:["countless","innumerable","multitude"],a:["few","limited"]},
{w:"naive",p:"adj.",k:"순진한",s:["gullible","credulous","innocent"],a:["worldly","cynical"]},
{w:"negate",p:"v.",k:"무효화하다, 부정하다",s:["nullify","invalidate","cancel"],a:["confirm","validate"]},
{w:"negligent",p:"adj.",k:"태만한",s:["careless","remiss","neglectful"],a:["diligent","careful"]},
{w:"nostalgia",p:"n.",k:"향수, 그리움",s:["longing","reminiscence","wistfulness"],a:["indifference",""]},
{w:"notorious",p:"adj.",k:"악명 높은",s:["infamous","disreputable","ill-famed"],a:["esteemed","respected"]},
{w:"novel",p:"adj.",k:"참신한, 새로운",s:["original","innovative","unprecedented"],a:["conventional","commonplace"]},
{w:"nuance",p:"n.",k:"미묘한 차이",s:["subtlety","shade","nicety"],a:["obviousness",""]},
{w:"obscure",p:"adj./v.",k:"불분명한; 가리다",s:["unclear","vague","conceal"],a:["clear","reveal"]},
{w:"obsolete",p:"adj.",k:"구식의, 폐기된",s:["outdated","antiquated","defunct"],a:["current","modern"]},
{w:"obstinate",p:"adj.",k:"고집 센",s:["stubborn","headstrong","inflexible"],a:["flexible","compliant"]},
{w:"ominous",p:"adj.",k:"불길한",s:["foreboding","threatening","sinister"],a:["auspicious","promising"]},
{w:"onerous",p:"adj.",k:"부담스러운, 힘겨운",s:["burdensome","demanding","taxing"],a:["effortless","light"]},
{w:"opaque",p:"adj.",k:"불투명한",s:["cloudy","obscure","impenetrable"],a:["transparent","clear"]},
{w:"ostentatious",p:"adj.",k:"과시하는",s:["showy","flamboyant","pretentious"],a:["modest","understated"]},
{w:"pacify",p:"v.",k:"진정시키다",s:["calm","placate","appease"],a:["provoke","incite"]},
{w:"paradox",p:"n.",k:"역설, 모순",s:["contradiction","anomaly","inconsistency"],a:["truism","consistency"]},
{w:"parody",p:"n.",k:"풍자, 패러디",s:["satire","spoof","caricature"],a:["tribute","homage"]},
{w:"partisan",p:"adj./n.",k:"편파적인; 당파주의자",s:["biased","factional","one-sided"],a:["impartial","neutral"]},
{w:"paucity",p:"n.",k:"결핍, 부족",s:["scarcity","dearth","shortage"],a:["abundance","plenty"]},
{w:"pensive",p:"adj.",k:"생각에 잠긴",s:["reflective","contemplative","thoughtful"],a:["carefree","unthinking"]},
{w:"perfunctory",p:"adj.",k:"형식적인, 성의 없는",s:["cursory","mechanical","superficial"],a:["thorough","conscientious"]},
{w:"peripheral",p:"adj.",k:"주변적인, 지엽적인",s:["marginal","secondary","tangential"],a:["central","essential"]},
{w:"pernicious",p:"adj.",k:"치명적인, 해로운",s:["harmful","destructive","injurious"],a:["beneficial","harmless"]},
{w:"pervasive",p:"adj.",k:"만연한",s:["widespread","prevalent","ubiquitous"],a:["rare","limited"]},
{w:"pious",p:"adj.",k:"경건한, 독실한",s:["devout","religious","reverent"],a:["impious","irreverent"]},
{w:"placate",p:"v.",k:"달래다",s:["appease","pacify","mollify"],a:["provoke","antagonize"]},
{w:"plausible",p:"adj.",k:"그럴듯한",s:["credible","believable","reasonable"],a:["implausible","unlikely"]},
{w:"plethora",p:"n.",k:"과다, 과잉",s:["excess","surplus","abundance"],a:["scarcity","dearth"]},
{w:"poignant",p:"adj.",k:"가슴 아픈, 절실한",s:["moving","touching","heart-rending"],a:["unmoving","trivial"]},
{w:"precarious",p:"adj.",k:"불안정한, 위태로운",s:["unstable","insecure","risky"],a:["stable","secure"]},
{w:"precedent",p:"n.",k:"선례",s:["antecedent","model","standard"],a:["novelty","innovation"]},
{w:"precocious",p:"adj.",k:"조숙한",s:["advanced","gifted","mature"],a:["backward","slow"]},
{w:"predominant",p:"adj.",k:"지배적인, 우세한",s:["prevailing","dominant","principal"],a:["minor","subordinate"]},
{w:"prevalent",p:"adj.",k:"만연한, 널리 퍼진",s:["widespread","common","predominant"],a:["rare","uncommon"]},
{w:"pristine",p:"adj.",k:"완전 새것 같은, 청정한",s:["unspoiled","immaculate","untouched"],a:["polluted","corrupted"]},
{w:"procrastinate",p:"v.",k:"미루다, 지연하다",s:["delay","postpone","defer"],a:["expedite","hasten"]},
{w:"prodigal",p:"adj.",k:"낭비하는",s:["wasteful","extravagant","profligate"],a:["frugal","thrifty"]},
{w:"profound",p:"adj.",k:"심오한",s:["deep","insightful","weighty"],a:["superficial","shallow"]},
{w:"proliferate",p:"v.",k:"급증하다, 확산되다",s:["multiply","spread","increase"],a:["diminish","decline"]},
{w:"prolific",p:"adj.",k:"다작의, 다산의",s:["productive","fruitful","abundant"],a:["barren","unproductive"]},
{w:"propensity",p:"n.",k:"경향, 성향",s:["tendency","inclination","predisposition"],a:["aversion","reluctance"]},
{w:"prosaic",p:"adj.",k:"평범한, 산문적인",s:["mundane","ordinary","dull"],a:["poetic","imaginative"]},
{w:"provocative",p:"adj.",k:"도발적인",s:["inflammatory","stimulating","challenging"],a:["soothing","placid"]},
{w:"prudent",p:"adj.",k:"신중한",s:["cautious","judicious","sensible"],a:["reckless","imprudent"]},
{w:"pugnacious",p:"adj.",k:"호전적인",s:["combative","belligerent","aggressive"],a:["peaceable","docile"]},
{w:"qualm",p:"n.",k:"불안, 거리낌",s:["misgiving","doubt","reservation"],a:["confidence","certainty"]},
{w:"quandary",p:"n.",k:"곤경, 딜레마",s:["dilemma","predicament","impasse"],a:["solution","resolution"]},
{w:"rebuttal",p:"n.",k:"반박",s:["refutation","counterargument","riposte"],a:["agreement","concession"]},
{w:"recalcitrant",p:"adj.",k:"반항적인, 고집 센",s:["defiant","obstinate","unruly"],a:["compliant","docile"]},
{w:"reciprocate",p:"v.",k:"보답하다, 화답하다",s:["return","requite","exchange"],a:["withhold","ignore"]},
{w:"redundant",p:"adj.",k:"불필요한, 중복된",s:["superfluous","unnecessary","repetitive"],a:["essential","necessary"]},
{w:"refute",p:"v.",k:"반박하다",s:["disprove","rebut","contradict"],a:["confirm","corroborate"]},
{w:"relegate",p:"v.",k:"좌천시키다, 격하하다",s:["demote","downgrade","banish"],a:["promote","elevate"]},
{w:"relinquish",p:"v.",k:"포기하다, 양도하다",s:["abandon","surrender","forgo"],a:["retain","keep"]},
{w:"reminisce",p:"v.",k:"회상하다",s:["recall","recollect","remember"],a:["forget","ignore"]},
{w:"renounce",p:"v.",k:"포기하다, 단념하다",s:["relinquish","abandon","disown"],a:["embrace","claim"]},
{w:"replete",p:"adj.",k:"가득한, 충만한",s:["full","abundant","teeming"],a:["devoid","empty"]},
{w:"reprehensible",p:"adj.",k:"비난받을 만한",s:["blameworthy","deplorable","shameful"],a:["commendable","admirable"]},
{w:"reproach",p:"v./n.",k:"비난(하다), 책망",s:["criticize","rebuke","admonish"],a:["praise","commend"]},
{w:"repudiate",p:"v.",k:"거부하다, 부인하다",s:["reject","disavow","renounce"],a:["accept","endorse"]},
{w:"rescind",p:"v.",k:"철회하다, 폐지하다",s:["revoke","annul","repeal"],a:["enact","implement"]},
{w:"reticent",p:"adj.",k:"과묵한, 말수가 적은",s:["reserved","taciturn","uncommunicative"],a:["talkative","forthcoming"]},
{w:"reverence",p:"n.",k:"존경, 경외",s:["respect","veneration","awe"],a:["disdain","contempt"]},
{w:"rhetoric",p:"n.",k:"수사법, 미사여구",s:["oratory","eloquence","wording"],a:["plainness",""]},
{w:"rigorous",p:"adj.",k:"엄격한, 철저한",s:["strict","stringent","exacting"],a:["lenient","lax"]},
{w:"sagacious",p:"adj.",k:"현명한, 통찰력 있는",s:["wise","shrewd","astute"],a:["foolish","obtuse"]},
{w:"salient",p:"adj.",k:"두드러진, 현저한",s:["prominent","conspicuous","notable"],a:["minor","insignificant"]},
{w:"sanguine",p:"adj.",k:"낙관적인",s:["optimistic","hopeful","upbeat"],a:["pessimistic","despondent"]},
{w:"scrupulous",p:"adj.",k:"양심적인, 세심한",s:["meticulous","conscientious","careful"],a:["unscrupulous","careless"]},
{w:"scrutinize",p:"v.",k:"세밀히 조사하다",s:["examine","inspect","analyze"],a:["overlook","ignore"]},
{w:"sedentary",p:"adj.",k:"앉아서 지내는",s:["inactive","stationary","sitting"],a:["active","mobile"]},
{w:"serendipity",p:"n.",k:"뜻밖의 발견, 행운",s:["chance","fluke","luck"],a:["misfortune","design"]},
{w:"servile",p:"adj.",k:"굽실거리는, 비굴한",s:["submissive","obsequious","subservient"],a:["assertive","dominant"]},
{w:"skeptic",p:"n.",k:"회의론자",s:["doubter","cynic","questioner"],a:["believer","zealot"]},
{w:"solace",p:"n.",k:"위안",s:["comfort","consolation","relief"],a:["distress","torment"]},
{w:"solicitous",p:"adj.",k:"염려하는, 배려하는",s:["concerned","attentive","caring"],a:["indifferent","careless"]},
{w:"sparse",p:"adj.",k:"희박한, 드문드문한",s:["scant","meager","scattered"],a:["dense","abundant"]},
{w:"spontaneous",p:"adj.",k:"자발적인, 즉흥적인",s:["impulsive","instinctive","unplanned"],a:["planned","deliberate"]},
{w:"sporadic",p:"adj.",k:"산발적인",s:["intermittent","occasional","irregular"],a:["constant","continuous"]},
{w:"spurious",p:"adj.",k:"가짜의, 거짓된",s:["false","fake","counterfeit"],a:["genuine","authentic"]},
{w:"stagnant",p:"adj.",k:"침체된, 정체된",s:["motionless","stale","inactive"],a:["dynamic","flourishing"]},
{w:"staunch",p:"adj.",k:"확고한, 충실한",s:["steadfast","loyal","resolute"],a:["fickle","disloyal"]},
{w:"stoic",p:"adj.",k:"금욕적인, 감정을 드러내지 않는",s:["impassive","unemotional","indifferent"],a:["emotional","expressive"]},
{w:"stringent",p:"adj.",k:"엄격한",s:["strict","rigorous","severe"],a:["lenient","lax"]},
{w:"subdue",p:"v.",k:"진압하다, 억누르다",s:["suppress","overpower","quell"],a:["incite","unleash"]},
{w:"subtle",p:"adj.",k:"미묘한",s:["nuanced","delicate","understated"],a:["obvious","blatant"]},
{w:"succinct",p:"adj.",k:"간결한",s:["concise","terse","brief"],a:["verbose","lengthy"]},
{w:"superficial",p:"adj.",k:"피상적인",s:["shallow","cursory","surface"],a:["profound","thorough"]},
{w:"superfluous",p:"adj.",k:"불필요한, 여분의",s:["redundant","excessive","unnecessary"],a:["essential","necessary"]},
{w:"surreptitious",p:"adj.",k:"은밀한",s:["covert","secretive","clandestine"],a:["open","overt"]},
{w:"sycophant",p:"n.",k:"아첨꾼",s:["flatterer","toady","yes-man"],a:["critic",""]},
{w:"tacit",p:"adj.",k:"암묵적인, 무언의",s:["implicit","unspoken","implied"],a:["explicit","stated"]},
{w:"tangible",p:"adj.",k:"만질 수 있는, 명백한",s:["concrete","palpable","real"],a:["intangible","abstract"]},
{w:"taut",p:"adj.",k:"팽팽한, 긴장된",s:["tight","tense","stretched"],a:["slack","loose"]},
{w:"tedious",p:"adj.",k:"지루한",s:["monotonous","dull","wearisome"],a:["engaging","exciting"]},
{w:"temperate",p:"adj.",k:"온화한, 절제된",s:["moderate","mild","restrained"],a:["extreme","intemperate"]},
{w:"tenacious",p:"adj.",k:"끈질긴, 집요한",s:["persistent","resolute","unyielding"],a:["irresolute","yielding"]},
{w:"tentative",p:"adj.",k:"잠정적인, 임시의",s:["provisional","preliminary","uncertain"],a:["definite","final"]},
{w:"terse",p:"adj.",k:"간결한, 무뚝뚝한",s:["curt","brusque","succinct"],a:["verbose","expansive"]},
{w:"torpid",p:"adj.",k:"무기력한, 활발하지 않은",s:["lethargic","sluggish","dormant"],a:["active","vigorous"]},
{w:"tranquil",p:"adj.",k:"고요한, 평온한",s:["calm","serene","peaceful"],a:["turbulent","chaotic"]},
{w:"transient",p:"adj.",k:"일시적인, 순간의",s:["temporary","fleeting","ephemeral"],a:["permanent","lasting"]},
{w:"trepidation",p:"n.",k:"불안, 두려움",s:["apprehension","anxiety","dread"],a:["confidence","calm"]},
{w:"trivial",p:"adj.",k:"사소한",s:["insignificant","minor","petty"],a:["significant","crucial"]},
{w:"ubiquitous",p:"adj.",k:"어디에나 있는",s:["omnipresent","pervasive","widespread"],a:["rare","scarce"]},
{w:"undermine",p:"v.",k:"약화시키다, 손상시키다",s:["weaken","subvert","erode"],a:["support","strengthen"]},
{w:"unequivocal",p:"adj.",k:"명백한, 모호하지 않은",s:["unambiguous","clear","definite"],a:["equivocal","ambiguous"]},
{w:"unprecedented",p:"adj.",k:"전례 없는",s:["unparalleled","unmatched","novel"],a:["customary","common"]},
{w:"unwarranted",p:"adj.",k:"부당한, 근거 없는",s:["unjustified","baseless","groundless"],a:["justified","warranted"]},
{w:"vacillate",p:"v.",k:"망설이다, 오락가락하다",s:["waver","fluctuate","hesitate"],a:["decide","commit"]},
{w:"vehement",p:"adj.",k:"격렬한, 강렬한",s:["intense","passionate","fervent"],a:["mild","indifferent"]},
{w:"venerate",p:"v.",k:"존경하다, 숭배하다",s:["revere","esteem","honor"],a:["despise","scorn"]},
{w:"veracity",p:"n.",k:"진실성, 정확성",s:["truthfulness","accuracy","honesty"],a:["falsehood","deceit"]},
{w:"verbose",p:"adj.",k:"장황한",s:["wordy","long-winded","prolix"],a:["concise","succinct"]},
{w:"viable",p:"adj.",k:"실행 가능한, 생존 가능한",s:["feasible","workable","practicable"],a:["unfeasible","impractical"]},
{w:"vindicate",p:"v.",k:"정당성을 입증하다, 혐의를 벗기다",s:["justify","exonerate","absolve"],a:["incriminate","condemn"]},
{w:"virtuoso",p:"n.",k:"거장, 명인",s:["maestro","master","expert"],a:["novice","amateur"]},
{w:"vivacious",p:"adj.",k:"활기찬, 명랑한",s:["lively","animated","spirited"],a:["listless","dull"]},
{w:"volatile",p:"adj.",k:"변덕스러운, 휘발성의",s:["unstable","erratic","explosive"],a:["stable","steady"]},
{w:"voracious",p:"adj.",k:"탐욕스러운, 왕성한",s:["insatiable","ravenous","greedy"],a:["moderate","satisfied"]},
{w:"wary",p:"adj.",k:"경계하는, 조심스러운",s:["cautious","vigilant","guarded"],a:["careless","incautious"]},
{w:"whimsical",p:"adj.",k:"엉뚱한, 변덕스러운",s:["fanciful","quirky","capricious"],a:["conventional","predictable"]},
{w:"zealous",p:"adj.",k:"열성적인",s:["enthusiastic","ardent","fervent"],a:["apathetic","indifferent"]},
{w:"accumulate",p:"v.",k:"축적하다",s:["amass","gather","collect"],a:["disperse","deplete"]},
{w:"advocate",p:"v./n.",k:"옹호하다; 지지자",s:["support","champion","proponent"],a:["oppose","opponent"]},
{w:"allocate",p:"v.",k:"할당하다, 배분하다",s:["assign","distribute","apportion"],a:["withhold","retain"]},
{w:"analogy",p:"n.",k:"유추, 비유",s:["comparison","parallel","correlation"],a:["contrast","disparity"]},
{w:"arbitrate",p:"v.",k:"중재하다",s:["mediate","adjudicate","settle"],a:["escalate","instigate"]},
{w:"assert",p:"v.",k:"주장하다, 단언하다",s:["declare","affirm","maintain"],a:["deny","refute"]},
{w:"attain",p:"v.",k:"달성하다",s:["achieve","accomplish","reach"],a:["fail","forfeit"]},
{w:"coincide",p:"v.",k:"일치하다, 동시에 일어나다",s:["correspond","align","concur"],a:["diverge","differ"]},
{w:"compensate",p:"v.",k:"보상하다",s:["reimburse","offset","recompense"],a:["deprive","penalize"]},
{w:"conceive",p:"v.",k:"생각해내다, 상상하다",s:["imagine","devise","formulate"],a:["disregard","abandon"]},
{w:"constitute",p:"v.",k:"구성하다",s:["comprise","form","make up"],a:["exclude","dissolve"]},
{w:"contradict",p:"v.",k:"모순되다, 반박하다",s:["oppose","refute","dispute"],a:["confirm","corroborate"]},
{w:"correlate",p:"v.",k:"상관관계를 갖다",s:["correspond","relate","associate"],a:["diverge","disconnect"]},
{w:"denote",p:"v.",k:"나타내다, 의미하다",s:["signify","indicate","represent"],a:["conceal","obscure"]},
{w:"derive",p:"v.",k:"유래하다, 이끌어내다",s:["originate","stem","obtain"],a:["create","invent"]},
{w:"discrete",p:"adj.",k:"별개의, 분리된",s:["separate","distinct","individual"],a:["continuous","unified"]},
{w:"distort",p:"v.",k:"왜곡하다",s:["misrepresent","warp","skew"],a:["clarify","reflect"]},
{w:"diverse",p:"adj.",k:"다양한",s:["varied","assorted","heterogeneous"],a:["uniform","homogeneous"]},
{w:"dominant",p:"adj.",k:"지배적인, 우세한",s:["predominant","prevailing","controlling"],a:["subordinate","minor"]},
{w:"empirical",p:"adj.",k:"경험적인, 실증적인",s:["observed","experiential","factual"],a:["theoretical","speculative"]},
{w:"ensure",p:"v.",k:"보장하다, 확실하게 하다",s:["guarantee","secure","confirm"],a:["jeopardize","risk"]},
{w:"equivalent",p:"adj.",k:"동등한",s:["equal","comparable","corresponding"],a:["different","unequal"]},
{w:"evaluate",p:"v.",k:"평가하다",s:["assess","appraise","judge"],a:["ignore","disregard"]},
{w:"evolve",p:"v.",k:"진화하다, 발전하다",s:["develop","progress","transform"],a:["stagnate","regress"]},
{w:"exceed",p:"v.",k:"초과하다",s:["surpass","outstrip","transcend"],a:["fall short","lag"]},
{w:"expand",p:"v.",k:"확장하다",s:["enlarge","broaden","extend"],a:["contract","shrink"]},
{w:"facilitate",p:"v.",k:"촉진하다, 용이하게 하다",s:["ease","expedite","assist"],a:["hinder","impede"]},
{w:"finite",p:"adj.",k:"유한한",s:["limited","bounded","restricted"],a:["infinite","boundless"]},
{w:"fluctuate",p:"v.",k:"변동하다",s:["vary","oscillate","waver"],a:["stabilize","remain"]},
{w:"formulate",p:"v.",k:"공식화하다, 만들어내다",s:["devise","develop","construct"],a:["dismantle","scrap"]},
{w:"illustrate",p:"v.",k:"설명하다, 예시를 들다",s:["exemplify","demonstrate","depict"],a:["obscure","confuse"]},
{w:"implement",p:"v.",k:"시행하다, 실행하다",s:["execute","enact","carry out"],a:["abandon","suspend"]},
{w:"incorporate",p:"v.",k:"통합하다, 포함하다",s:["integrate","include","embody"],a:["exclude","separate"]},
{w:"inhibit",p:"v.",k:"억제하다",s:["restrain","hinder","suppress"],a:["encourage","promote"]},
{w:"integrate",p:"v.",k:"통합하다",s:["combine","merge","unify"],a:["separate","segregate"]},
{w:"intervene",p:"v.",k:"개입하다",s:["interfere","mediate","interpose"],a:["abstain","withdraw"]},
{w:"intrinsic",p:"adj.",k:"본질적인, 내재하는",s:["inherent","innate","fundamental"],a:["extrinsic","external"]},
{w:"manipulate",p:"v.",k:"조작하다",s:["control","influence","handle"],a:["neglect","ignore"]},
{w:"neutral",p:"adj.",k:"중립적인",s:["impartial","unbiased","nonaligned"],a:["partisan","biased"]},
{w:"obtain",p:"v.",k:"얻다, 획득하다",s:["acquire","secure","gain"],a:["lose","forfeit"]},
{w:"perceive",p:"v.",k:"인지하다, 인식하다",s:["discern","recognize","observe"],a:["overlook","misunderstand"]},
{w:"phenomenon",p:"n.",k:"현상",s:["occurrence","event","happening"],a:["nonoccurrence",""]},
{w:"precise",p:"adj.",k:"정확한",s:["exact","accurate","specific"],a:["vague","imprecise"]},
{w:"predict",p:"v.",k:"예측하다",s:["forecast","foresee","anticipate"],a:["misjudge",""]},
{w:"prohibit",p:"v.",k:"금지하다",s:["ban","forbid","outlaw"],a:["permit","allow"]},
{w:"pursue",p:"v.",k:"추구하다",s:["chase","seek","strive for"],a:["abandon","relinquish"]},
{w:"random",p:"adj.",k:"무작위의",s:["arbitrary","haphazard","indiscriminate"],a:["systematic","deliberate"]},
{w:"reinforce",p:"v.",k:"강화하다",s:["strengthen","bolster","fortify"],a:["weaken","undermine"]},
{w:"reject",p:"v.",k:"거부하다",s:["decline","refuse","dismiss"],a:["accept","approve"]},
{w:"relevant",p:"adj.",k:"관련 있는",s:["pertinent","applicable","germane"],a:["irrelevant","unrelated"]},
{w:"restrain",p:"v.",k:"억제하다, 제지하다",s:["curb","control","hold back"],a:["release","unleash"]},
{w:"reveal",p:"v.",k:"드러내다, 밝히다",s:["disclose","expose","divulge"],a:["conceal","hide"]},
{w:"rigid",p:"adj.",k:"엄격한, 경직된",s:["strict","inflexible","stiff"],a:["flexible","adaptable"]},
{w:"significant",p:"adj.",k:"중요한, 상당한",s:["important","substantial","notable"],a:["insignificant","trivial"]},
{w:"stable",p:"adj.",k:"안정된",s:["steady","secure","constant"],a:["unstable","volatile"]},
{w:"substitute",p:"v./n.",k:"대체하다; 대체물",s:["replace","swap","surrogate"],a:["retain","original"]},
{w:"sufficient",p:"adj.",k:"충분한",s:["adequate","ample","enough"],a:["insufficient","inadequate"]},
{w:"sustain",p:"v.",k:"지속시키다, 유지하다",s:["maintain","support","prolong"],a:["abandon","discontinue"]},
{w:"transform",p:"v.",k:"변형시키다",s:["convert","alter","transmute"],a:["preserve","maintain"]},
{w:"undergo",p:"v.",k:"겪다, 경험하다",s:["experience","endure","sustain"],a:["avoid","escape"]},
{w:"underlie",p:"v.",k:"기저를 이루다",s:["support","ground","form the basis of"],a:["overlay",""]},
{w:"uniform",p:"adj.",k:"균일한, 획일적인",s:["consistent","homogeneous","identical"],a:["varied","diverse"]},
{w:"unify",p:"v.",k:"통합하다, 단일화하다",s:["unite","merge","consolidate"],a:["divide","fragment"]},
{w:"unique",p:"adj.",k:"독특한, 유일한",s:["distinctive","singular","unparalleled"],a:["common","ordinary"]},
{w:"valid",p:"adj.",k:"타당한, 유효한",s:["sound","legitimate","justified"],a:["invalid","unsound"]},
{w:"vary",p:"v.",k:"다양하다, 변화하다",s:["differ","fluctuate","diverge"],a:["remain","stay constant"]},
{w:"violate",p:"v.",k:"위반하다, 침해하다",s:["breach","infringe","transgress"],a:["comply","observe"]},
{w:"visible",p:"adj.",k:"눈에 보이는",s:["apparent","evident","observable"],a:["invisible","hidden"]},
{w:"widespread",p:"adj.",k:"널리 퍼진",s:["prevalent","extensive","pervasive"],a:["localized","limited"]},
];

// 브라우저 전역에 노출
if (typeof window !== "undefined") {
  window.TOEFL_WORDS = TOEFL_WORDS;
}
